name: mdbook build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: '0.4.36'
      MDBOOK_ADMONISH_VERSION: '1.15.0'
      MDBOOK_MERMAID_VERSION: '0.13.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mdbook
        run: |
          mkdir -p ~/bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory ~/bin
      - name: Install mdbook-admonish
        run: |
          mkdir -p ~/bin
          curl -sSL https://github.com/tommilligan/mdbook-admonish/releases/download/v${MDBOOK_ADMONISH_VERSION}/mdbook-admonish-v${MDBOOK_ADMONISH_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory ~/bin
      - name: Install mdbook-mermaid
        run: |
          mkdir -p ~/bin
          curl -sSL https://github.com/badboy/mdbook-mermaid/releases/download/v${MDBOOK_MERMAID_VERSION}/mdbook-mermaid-v${MDBOOK_MERMAID_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory ~/bin
      - name: Setup PATH
        run: echo ~/bin >> $GITHUB_PATH
      - name: Run mdbook build
        run: mdbook build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: book/
